=== tjwoodall/individuals-charges-api/resources/public/api/conf/3.0/schemas/pensionCharges/createAmend/def1/create_amend_request_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Tax years before 2024-25",
  "description": "Create and Amend Pension Charges",
  "type": "object",
  "properties": {
    "pensionSavingsTaxCharges": {
      "type": "object",
      "description": "Object holding the booleans for annual allowance.\n\n<b>NOTE:</b> Since April 2024, HMRC customers can no longer submit their pension lifetime allowance.\n\nThe <code>lumpSumBenefitTakenInExcessOfLifetimeAllowance</code> and <code>benefitInExcessOfLifetimeAllowance</code> objects within <code>pensionSavingsTaxCharges</code> are now obsolete and will be removed in a future update. <b>Do not submit values for these objects</b>.",
      "properties": {
        "pensionSchemeTaxReference": {
          "type": "array",
          "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
          "items": {
            "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
            "type": "string",
            "example": "00123456RA"
          }
        },
        "lumpSumBenefitTakenInExcessOfLifetimeAllowance": {
          "type": "object",
          "description": "Object holding the amount and tax paid on lump sum benefit in excess of the lifetime allowance.",
          "properties": {
            "amount": {
              "description": "The amount of the lump sum benefit taken in excess of the lifetime allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            },
            "taxPaid": {
              "description": "The amount of tax to be paid on the lump sum benefit taken in excess of the lifetime allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            }
          },
          "required": [
            "amount",
            "taxPaid"
          ]
        },
        "benefitInExcessOfLifetimeAllowance": {
          "type": "object",
          "description": "The amount and tax paid on benefit in excess of the lifetime allowance.",
          "properties": {
            "amount": {
              "description": "The amount of the benefit taken in excess of the lifetime allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            },
            "taxPaid": {
              "description": "The tax to be paid on the benefit taken in excess of the lifetime allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            }
          },
          "required": [
            "amount",
            "taxPaid"
          ]
        }
      },
      "required": [
        "pensionSchemeTaxReference"
      ]
    },
    "pensionSchemeOverseasTransfers": {
      "type": "object",
      "description": "Transfer of overseas pension to another pension scheme.",
      "properties": {
        "overseasSchemeProvider": {
          "description": "Details of overseas pension provider.",
          "type": "array",
          "items": {
            "oneOf": [
              {
                "title": "qualifyingRecognisedOverseasPensionScheme",
                "type": "object",
                "properties": {
                  "providerName": {
                    "description": "The name of the pension provider. Must not be empty or contain only whitespace.",
                    "type": "string",
                    "pattern": "^.{1,105}$",
                    "example": "Overseas Pensions Plc"
                  },
                  "providerAddress": {
                    "description": "The address of the pension provider. Must not be empty or contain only whitespace.",
                    "type": "string",
                    "pattern": "^.{1,250}$",
                    "example": "111 Main Street, Any Town, Any City"
                  },
                  "providerCountryCode": {
                    "description": "A three-letter code that represents a country name. The value must be a ISO 3166-1 alpha-3 code.",
                    "type": "string",
                    "example": "CYM"
                  },
                  "qualifyingRecognisedOverseasPensionScheme": {
                    "type": "array",
                    "description": "A list of one or more qualifying overseas pension scheme reference numbers for overseas pensions contributions.",
                    "items": {
                      "pattern": "^[Q]{1}[0-9]{6}$",
                      "type": "string",
                      "example": "Q123456"
                    }
                  }
                },
                "required": [
                  "providerName",
                  "providerAddress",
                  "providerCountryCode"
                ]
              },
              {
                "title": "pensionSchemeTaxReference",
                "type": "object",
                "properties": {
                  "providerName": {
                    "description": "The name of the pension provider. Must not be empty or contain only whitespace.",
                    "type": "string",
                    "pattern": "^.{1,105}$",
                    "example": "Overseas Pensions Plc"
                  },
                  "providerAddress": {
                    "description": "The address of the pension provider. Must not be empty or contain only whitespace.",
                    "type": "string",
                    "pattern": "^.{1,250}$",
                    "example": "111 Main Street, Any Town, Any City"
                  },
                  "providerCountryCode": {
                    "description": "A three-letter code that represents a country name. The value must be a ISO 3166-1 alpha-3 code.",
                    "type": "string",
                    "example": "CYM"
                  },
                  "pensionSchemeTaxReference": {
                    "type": "array",
                    "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
                    "items": {
                      "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
                      "type": "string",
                      "example": "00123456RA"
                    }
                  }
                },
                "required": [
                  "providerName",
                  "providerAddress",
                  "providerCountryCode"
                ]
              }
            ]
          }
        },
        "transferCharge": {
          "description": "The amount the pension provider charges to transfer the pension. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        },
        "transferChargeTaxPaid": {
          "description": "The amount of tax paid on the transfer charge. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        }
      },
      "required": [
        "overseasSchemeProvider",
        "transferCharge",
        "transferChargeTaxPaid"
      ]
    },
    "pensionSchemeUnauthorisedPayments": {
      "type": "object",
      "description": "Tax on unauthorised payment.",
      "properties": {
        "pensionSchemeTaxReference": {
          "type": "array",
          "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
          "items": {
            "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
            "type": "string",
            "example": "00123456RA"
          }
        },
        "surcharge": {
          "type": "object",
          "description": "Object holding the unauthorised payments surcharge.",
          "properties": {
            "amount": {
              "description": "The amount of the unauthorised payment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            },
            "foreignTaxPaid": {
              "description": "The amount of foreign tax paid in pounds sterling. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            }
          },
          "required": [
            "amount",
            "foreignTaxPaid"
          ]
        },
        "noSurcharge": {
          "type": "object",
          "description": "Object holding the unauthorised payments no surcharge.",
          "properties": {
            "amount": {
              "description": "The amount of the unauthorised payment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            },
            "foreignTaxPaid": {
              "description": "The amount of foreign tax paid in pounds sterling. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            }
          },
          "required": [
            "amount",
            "foreignTaxPaid"
          ]
        }
      },
      "required": [
        "pensionSchemeTaxReference"
      ]
    },
    "pensionContributions": {
      "type": "object",
      "description": " Payments paid into a pension.",
      "properties": {
        "pensionSchemeTaxReference": {
          "type": "array",
          "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
          "items": {
            "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
            "type": "string",
            "example": "00123456RA"
          }
        },
        "inExcessOfTheAnnualAllowance": {
          "description": "The amount of the in excess of the annual allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        },
        "annualAllowanceTaxPaid": {
          "description": "The amount of tax paid on annual allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        },
        "isAnnualAllowanceReduced": {
          "description": "A boolean indicating whether annual allowance has been reduced. If this field is set to true then at least one of taperedAnnualAllowance or moneyPurchasedAllowance must also be set to true.",
          "type": "boolean",
          "example": false
        },
        "taperedAnnualAllowance": {
          "description": "A boolean indicating whether tapered annual allowance is lower than the standard annual allowance. The value must be true or false.",
          "type": "boolean",
          "example": true
        },
        "moneyPurchasedAllowance": {
          "description": "A boolean indicating whether the person has paid the maximum amount allowed for their reduced allowance, based on Money Purchase Annual Allowance (MPAA). The value must be true or false. For example: false",
          "type": "boolean",
          "example": false
        }
      },
      "required": [
        "pensionSchemeTaxReference",
        "inExcessOfTheAnnualAllowance",
        "annualAllowanceTaxPaid",
        "isAnnualAllowanceReduced"
      ]
    },
    "overseasPensionContributions": {
      "type": "object",
      "description": "Object holding contributions paid into overseas pension.",
      "properties": {
        "overseasSchemeProvider": {
          "description": "Details of overseas pension provider.",
          "type": "array",
          "items": {
            "oneOf": [
              {
                "title": "qualifyingRecognisedOverseasPensionScheme",
                "type": "object",
                "properties": {
                  "providerName": {
                    "description": "The name of the pension provider. Must not be empty or contain only whitespace.",
                    "type": "string",
                    "pattern": "^.{1,105}$",
                    "example": "Overseas Pensions Plc"
                  },
                  "providerAddress": {
                    "description": "The address of the pension provider. Must not be empty or contain only whitespace.",
                    "type": "string",
                    "pattern": "^.{1,250}$",
                    "example": "111 Main Street, Any Town, Any City"
                  },
                  "providerCountryCode": {
                    "description": "A three-letter code that represents a country name. The value must be a ISO 3166-1 alpha-3 code.",
                    "type": "string",
                    "example": "CYM"
                  },
                  "qualifyingRecognisedOverseasPensionScheme": {
                    "type": "array",
                    "description": "A list of one or more qualifying overseas pension scheme reference numbers for overseas pensions contributions.",
                    "items": {
                      "pattern": "^[Q]{1}[0-9]{6}$",
                      "type": "string",
                      "example": "Q123456"
                    }
                  }
                },
                "required": [
                  "providerName",
                  "providerAddress",
                  "providerCountryCode"
                ]
              },
              {
                "title": "pensionSchemeTaxReference",
                "type": "object",
                "properties": {
                  "providerName": {
                    "description": "The name of the pension provider. Must not be empty or contain only whitespace.",
                    "type": "string",
                    "pattern": "^.{1,105}$",
                    "example": "Overseas Pensions Plc"
                  },
                  "providerAddress": {
                    "description": "The address of the pension provider. Must not be empty or contain only whitespace.",
                    "type": "string",
                    "pattern": "^.{1,250}$",
                    "example": "111 Main Street, Any Town, Any City"
                  },
                  "providerCountryCode": {
                    "description": "A three-letter code that represents a country name. The value must be a ISO 3166-1 alpha-3 code.",
                    "type": "string",
                    "example": "CYM"
                  },
                  "pensionSchemeTaxReference": {
                    "type": "array",
                    "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
                    "items": {
                      "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
                      "type": "string",
                      "example": "00123456RA"
                    }
                  }
                },
                "required": [
                  "providerName",
                  "providerAddress",
                  "providerCountryCode"
                ]
              }
            ]
          }
        },
        "shortServiceRefund": {
          "description": "The amount of short service refund for overseas pension contributions. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        },
        "shortServiceRefundTaxPaid": {
          "description": "The amount of tax paid on short service refund. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        }
      },
      "required": [
        "overseasSchemeProvider",
        "shortServiceRefund",
        "shortServiceRefundTaxPaid"
      ]
    }
  },
  "additionalProperties": false
}

=== tjwoodall/individuals-charges-api/resources/public/api/conf/3.0/examples/pensionCharges/createAmend/def1/create_amend_request.json
{
  "pensionSavingsTaxCharges": {
    "pensionSchemeTaxReference": [
      "00123456RA",
      "00123456RB"
    ],
    "lumpSumBenefitTakenInExcessOfLifetimeAllowance": {
      "amount": 100,
      "taxPaid": 100
    },
    "benefitInExcessOfLifetimeAllowance": {
      "amount": 100,
      "taxPaid": 100
    }
  },
  "pensionSchemeOverseasTransfers": {
    "overseasSchemeProvider": [
      {
        "providerName": "Overseas Pensions Plc",
        "providerAddress": "111 Main Street, George Town, Grand Cayman",
        "providerCountryCode": "CYM",
        "qualifyingRecognisedOverseasPensionScheme": [
          "Q123456"
        ]
      }
    ],
    "transferCharge": 100,
    "transferChargeTaxPaid": 100
  },
  "pensionSchemeUnauthorisedPayments": {
    "pensionSchemeTaxReference": [
      "00123456RA",
      "00123456RB"
    ],
    "surcharge": {
      "amount": 100,
      "foreignTaxPaid": 100
    },
    "noSurcharge": {
      "amount": 100,
      "foreignTaxPaid": 100
    }
  },
  "pensionContributions": {
    "pensionSchemeTaxReference": [
      "00123456RA",
      "00123456RB"
    ],
    "inExcessOfTheAnnualAllowance": 100,
    "annualAllowanceTaxPaid": 100,
    "isAnnualAllowanceReduced": true,
    "taperedAnnualAllowance": true,
    "moneyPurchasedAllowance": false
  },
  "overseasPensionContributions": {
    "overseasSchemeProvider": [
      {
        "providerName": "Overseas Pensions Plc",
        "providerAddress": "111 Main Street, George Town, Grand Cayman",
        "providerCountryCode": "CYM",
        "qualifyingRecognisedOverseasPensionScheme": [
          "Q123456"
        ]
      }
    ],
    "shortServiceRefund": 123.0,
    "shortServiceRefundTaxPaid": 123.0
  }
}
