=== tjwoodall/individuals-charges-api/resources/public/api/conf/3.0/schemas/pensionCharges/retrieve/def2/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Tax years 2024-25 onwards",
  "description": "Retrieve Pension Charges",
  "type": "object",
  "properties": {
    "submittedOn": {
      "type": "string",
      "format": "date-time",
      "description": "An ISO-8601 compliant date-time representing when pension charges were submitted.",
      "example": "2021-04-04T01:01:01.000Z",
      "pattern": "^2[0-9]{3}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{0,3}Z$"
    },
    "pensionSchemeOverseasTransfers": {
      "type": "object",
      "description": "Object holding the transfer of overseas pension to another pension scheme.",
      "properties": {
        "overseasSchemeProvider": {
          "description": "Details of overseas pension provider.",
          "type": "array",
          "items": {
            "title": "item",
            "type": "object",
            "properties": {
              "providerName": {
                "description": "The name of the pension provider. Must not be empty or contain only whitespace.",
                "type": "string",
                "pattern": "^.{1,105}$",
                "example": "Overseas Pensions Plc"
              },
              "providerAddress": {
                "description": "The address of the pension provider. Must not be empty or contain only whitespace.",
                "type": "string",
                "pattern": "^.{1,250}$",
                "example": "111 Main Street, Any Town, Any City"
              },
              "providerCountryCode": {
                "description": "A three-letter code that represents a country name. The value must be a ISO 3166-1 alpha-3 code.",
                "type": "string",
                "example": "CYM"
              },
              "qualifyingRecognisedOverseasPensionScheme": {
                "type": "array",
                "description": "A list of one or more qualifying overseas pension scheme reference numbers for overseas pensions contributions.",
                "items": {
                  "pattern": "^[Q]{1}[0-9]{6}$",
                  "type": "string",
                  "example": "Q123456"
                }
              },
              "pensionSchemeTaxReference": {
                "type": "array",
                "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
                "items": {
                  "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
                  "type": "string",
                  "example": "00123456RA"
                }
              }
            },
            "required": [
              "providerName",
              "providerAddress",
              "providerCountryCode"
            ]
          }
        },
        "transferCharge": {
          "description": "The amount the pension provider charges to transfer the pension. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        },
        "transferChargeTaxPaid": {
          "description": "The amount of tax paid on the transfer charge. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        }
      },
      "required": [
        "overseasSchemeProvider",
        "transferCharge",
        "transferChargeTaxPaid"
      ]
    },
    "pensionSchemeUnauthorisedPayments": {
      "type": "object",
      "description": "Object holding tax on unauthorised payment.",
      "properties": {
        "pensionSchemeTaxReference": {
          "type": "array",
          "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
          "items": {
            "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
            "type": "string",
            "example": "00123456RA"
          }
        },
        "surcharge": {
          "type": "object",
          "description": "The unauthorised payments surcharge.",
          "properties": {
            "amount": {
              "description": "The amount of the unauthorised payment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            },
            "foreignTaxPaid": {
              "description": "The amount of foreign tax paid in pounds sterling. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            }
          },
          "required": [
            "amount",
            "foreignTaxPaid"
          ]
        },
        "noSurcharge": {
          "type": "object",
          "description": "Object holding unauthorised payments for no surcharge.",
          "properties": {
            "amount": {
              "description": "The amount of the unauthorised payment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            },
            "foreignTaxPaid": {
              "description": "The amount of foreign tax paid in pounds sterling. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type": "number",
              "multipleOf": 0.01,
              "minimum": 0,
              "maximum": 99999999999.99,
              "example": 1999.99
            }
          },
          "required": [
            "amount",
            "foreignTaxPaid"
          ]
        }
      }
    },
    "pensionContributions": {
      "type": "object",
      "description": "Object holding payments paid into a pension",
      "properties": {
        "pensionSchemeTaxReference": {
          "type": "array",
          "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
          "items": {
            "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
            "type": "string",
            "example": "00123456RA"
          }
        },
        "inExcessOfTheAnnualAllowance": {
          "description": "The amount of the in excess of the annual allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        },
        "annualAllowanceTaxPaid": {
          "description": "The amount of tax paid on annual allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        },
        "isAnnualAllowanceReduced": {
          "description": "A boolean indicating whether annual allowance has been reduced. The value must be true or false. If isAnnualAllowanceReduced is true then either taperedAnnualAllowance or moneyPurchasedAllowance must be true as well.",
          "type": "boolean",
          "example": false
        },
        "taperedAnnualAllowance": {
          "description": "A boolean indicating whether tapered annual allowance is lower than the standard annual allowance. The value must be true or false.",
          "type": "boolean",
          "example": true
        },
        "moneyPurchasedAllowance": {
          "description": "A boolean indicating whether the person has paid the maximum amount allowed for their reduced allowance, based on Money Purchase Annual Allowance (MPAA). The value must be true or false. For example: false",
          "type": "boolean",
          "example": false
        }
      },
      "required": [
        "pensionSchemeTaxReference",
        "inExcessOfTheAnnualAllowance",
        "annualAllowanceTaxPaid"
      ]
    },
    "overseasPensionContributions": {
      "type": "object",
      "description": "Object holding the contributions paid into overseas pension.",
      "properties": {
        "overseasSchemeProvider": {
          "description": "Details of overseas pension provider.",
          "type": "array",
          "items": {
            "title": "item",
            "type": "object",
            "properties": {
              "providerName": {
                "description": "The name of the pension provider. Must not be empty or contain only whitespace.",
                "type": "string",
                "pattern": "^.{1,105}$",
                "example": "Overseas Pensions Plc"
              },
              "providerAddress": {
                "description": "The address of the pension provider. Must not be empty or contain only whitespace.",
                "type": "string",
                "pattern": "^.{1,250}$",
                "example": "111 Main Street, Any Town, Any City"
              },
              "providerCountryCode": {
                "description": "A three-letter code that represents a country name. The value must be a ISO 3166-1 alpha-3 code.",
                "type": "string",
                "example": "CYM"
              },
              "qualifyingRecognisedOverseasPensionScheme": {
                "type": "array",
                "description": "A list of one or more qualifying overseas pension scheme reference numbers for overseas pensions contributions.",
                "items": {
                  "pattern": "^[Q]{1}[0-9]{6}$",
                  "type": "string",
                  "example": "Q123456"
                }
              },
              "pensionSchemeTaxReference": {
                "type": "array",
                "description": "A list of one or more unique references provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
                "items": {
                  "pattern": "^\\d{8}[R]{1}[a-zA-Z]{1}$",
                  "type": "string",
                  "example": "00123456RA"
                }
              }
            },
            "required": [
              "providerName",
              "providerAddress",
              "providerCountryCode"
            ]
          }
        },
        "shortServiceRefund": {
          "description": "The amount of short service refund for overseas pension contributions. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        },
        "shortServiceRefundTaxPaid": {
          "description": "The amount of tax paid on short service refund. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type": "number",
          "multipleOf": 0.01,
          "minimum": 0,
          "maximum": 99999999999.99,
          "example": 1999.99
        }
      },
      "required": [
        "overseasSchemeProvider",
        "shortServiceRefund",
        "shortServiceRefundTaxPaid"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "submittedOn"
  ]
}

=== tjwoodall/individuals-charges-api/resources/public/api/conf/3.0/examples/pensionCharges/retrieve/def2/response.json
{
  "submittedOn": "2024-07-27T17:00:19.000Z",
  "pensionSchemeOverseasTransfers": {
    "overseasSchemeProvider": [
      {
        "providerName": "Overseas Pensions Plc.",
        "providerAddress": "111 Main Street, Any Town, Any City",
        "providerCountryCode": "CYM",
        "qualifyingRecognisedOverseasPensionScheme": [
          "Q123456"
        ]
      }
    ],
    "transferCharge": 100,
    "transferChargeTaxPaid": 100
  },
  "pensionSchemeUnauthorisedPayments": {
    "pensionSchemeTaxReference": [
      "00123456RA",
      "00123456RB"
    ],
    "surcharge": {
      "amount": 100.99,
      "foreignTaxPaid": 100.99
    },
    "noSurcharge": {
      "amount": 100.99,
      "foreignTaxPaid": 100.99
    }
  },
  "pensionContributions": {
    "pensionSchemeTaxReference": [
      "00123456RA",
      "00123456RB"
    ],
    "inExcessOfTheAnnualAllowance": 100,
    "annualAllowanceTaxPaid": 100,
    "isAnnualAllowanceReduced": true,
    "taperedAnnualAllowance": true,
    "moneyPurchasedAllowance": false
  },
  "overseasPensionContributions": {
    "overseasSchemeProvider": [
      {
        "providerName": "Overseas Pensions Plc",
        "providerAddress": "111 Main Street, Any Town, Any City",
        "providerCountryCode": "CYM",
        "qualifyingRecognisedOverseasPensionScheme": [
          "Q123456"
        ]
      }
    ],
    "shortServiceRefund": 123.0,
    "shortServiceRefundTaxPaid": 123.0
  }
}
